/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShoppingList } from './shopping-list.model';


export interface Item { 
    id?: number;
    shoppingList?: ShoppingList;
    name?: string;
    description?: string;
    isBought?: boolean;
    createdAt?: Date;
}

