/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShoppingListResponse { 
    id?: number;
    name?: string;
    ownerId?: number;
    isOwner?: boolean;
    shareToken?: string;
    createdAt?: Date;
    updatedAt?: Date;
}

