/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Item } from './item.model';
import { User } from './user.model';
import { ShoppingListShare } from './shopping-list-share.model';


export interface ShoppingList { 
    id?: number;
    owner?: User;
    name?: string;
    shareToken?: string;
    createdAt?: Date;
    updatedAt?: Date;
    items?: Array<Item>;
    shares?: Array<ShoppingListShare>;
}

