/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user.model';
import { ShoppingList } from './shopping-list.model';
import { ShoppingListShareId } from './shopping-list-share-id.model';


export interface ShoppingListShare { 
    id?: ShoppingListShareId;
    shoppingList?: ShoppingList;
    user?: User;
}

