/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ShoppingList } from './shopping-list.model';
import { GrantedAuthority } from './granted-authority.model';
import { ShoppingListShare } from './shopping-list-share.model';


export interface User { 
    id?: number;
    email?: string;
    passwordHash?: string;
    createdAt?: Date;
    ownedLists?: Array<ShoppingList>;
    sharedLists?: Array<ShoppingListShare>;
    authorities?: Array<GrantedAuthority>;
    password?: string;
    username?: string;
    enabled?: boolean;
    accountNonExpired?: boolean;
    accountNonLocked?: boolean;
    credentialsNonExpired?: boolean;
}

